# Default values for ninjam-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: zeppelinux/ninjam-server
  tag: v0.082
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 2049
  externalTrafficPolicy: Cluster


nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

  accessMode: ReadWriteOnce
  size: 3Gi
  ## ninjam session Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  #storageClass: longhorn
